# uses表示使用一些第三方库

# actions的名称
name: 更新文档到服务器

on:
  push:
    # push 代码的时候，监听该分支的改变
    branches:
      - master

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取代码
        uses: actions/checkout@master

      # 将打包后的文件上传到服务器
      - name: 发布到服务器
        # https://github.com/easingthemes/ssh-deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: '120.25.124.101'
          username: 'root'
          password: 'qQ1764728432'
          port: '22'
          source: 'dist/a.html'
          target: '/var/www/html/aa'
