# uses表示使用一些第三方库

# actions的名称
name: 更新文档到服务器

on:
  push:
    # push 代码的时候，监听该分支的改变
    branches:
      - master

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure .ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Add remote host to known_hosts
        run: ssh-keyscan -p 22 -H 120.25.124.101 >> ~/.ssh/known_hosts

      - name: Copy files to remote server
        run: rsync -avzr --delete -e "ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no" .vitepress/dist/ root@120.25.124.101:/var/www/html/blog

      - name: Execute remote script
        run: ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no root@120.25.124.101 "bash -s" < local_ssh_script.sh

        # 获取代码
        # - name: 迁出代码
        #   # 使用action库 action/checkout获取代码
        #   uses: actions/checkout@master

        # # 将打包后的文件上传到服务器
        # - name: 发布到服务器
        #   # https://github.com/easingthemes/ssh-deploy
        #   uses: easingthemes/ssh-deploy@main
        #   with:
        #     # 私钥
        #     SSH_PRIVATE_KEY: ${{ secrets.BYW_PRIVATE_KEY }}
        #     # SCP参数
        #     ARGS: '-avzr --delete'
        #     # 服务器ip
        #     REMOTE_HOST: '120.25.124.101'
        #     # 用户
        #     REMOTE_USER: 'root'
        #     # 源目录
        #     SOURCE: 'dist/'
        #     # 目标地址
        #     TARGET: '/var/www/html/aa'
        #     SCRIPT_BEFORE: 'ls'
